### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by jinek** [manuel-rhdt/snd-microbookii#4]
Is it possible to install this driver with out of compilation? If no would be great to have this feature.

**Comment by manuel-rhdt** [comment]
This is not possible with the linux kernel in general, because everyone uses a different kernel version thus and would need a differently compiled driver. I'm afraid you have to compile the module yourself (DKMS does make this quite easy though).

I also have no interest in providing any kind of installer but you can ask for help if you have problems.
